# Generated by Django 4.1.5 on 2023-01-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='hidden_password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
